# Use root/example as user/password credentials
version: '3.1'

services:

  pd:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../pg-data:/var/lib/postgres/data